package dk.skat.dmr._2007._05._31;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2018-10-26T14:02:39.603+02:00
 * Generated source version: 3.1.9
 * 
 */
@WebServiceClient(name = "USForsikringService", 
                  wsdlLocation = "https://dmrsit1gateway1.skat.dk/B2B/USForsikring/Service?wsdl",
                  targetNamespace = "http://skat.dk/dmr/2007/05/31/") 
public class USForsikringService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://skat.dk/dmr/2007/05/31/", "USForsikringService");
    public final static QName Port = new QName("http://skat.dk/dmr/2007/05/31/", "Port");
    static {
        URL url = null;
        try {
            url = new URL("https://dmrsit1gateway1.skat.dk/B2B/USForsikring/Service?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(USForsikringService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://dmrsit1gateway1.skat.dk/B2B/USForsikring/Service?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public USForsikringService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public USForsikringService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public USForsikringService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public USForsikringService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public USForsikringService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public USForsikringService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns USForsikringServiceType
     */
    @WebEndpoint(name = "Port")
    public USForsikringServiceType getPort() {
        return super.getPort(Port, USForsikringServiceType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns USForsikringServiceType
     */
    @WebEndpoint(name = "Port")
    public USForsikringServiceType getPort(WebServiceFeature... features) {
        return super.getPort(Port, USForsikringServiceType.class, features);
    }

}
