package dk.skat.dmr._2007._05._31;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2018-10-26T14:02:39.553+02:00
 * Generated source version: 3.1.9
 * 
 */
@WebService(targetNamespace = "http://skat.dk/dmr/2007/05/31/", name = "USForsikringServiceType")
@XmlSeeAlso({ObjectFactory.class, dk.oio.rep.skat_dk.basis.kontekst.xml.schemas._2006._09._01.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface USForsikringServiceType {

    @WebResult(name = "USKoeretoejRegistreringHent_O", targetNamespace = "http://skat.dk/dmr/2007/05/31/", partName = "Response")
    @WebMethod(action = "getUSKoeretoejRegistreringHent")
    public USKoeretoejRegistreringHentO getUSKoeretoejRegistreringHent(
        @WebParam(partName = "Request", name = "USKoeretoejRegistreringHent_I", targetNamespace = "http://skat.dk/dmr/2007/05/31/")
        USKoeretoejRegistreringHentI request
    );

    @WebResult(name = "USKoeretoejBetegnelseHierarkiListeHent_O", targetNamespace = "http://skat.dk/dmr/2007/05/31/", partName = "Response")
    @WebMethod(action = "getUSKoeretoejBetegnelseHierarkiListeHent")
    public USKoeretoejBetegnelseHierarkiListeHentO getUSKoeretoejBetegnelseHierarkiListeHent(
        @WebParam(partName = "Request", name = "USKoeretoejBetegnelseHierarkiListeHent_I", targetNamespace = "http://skat.dk/dmr/2007/05/31/")
        USKoeretoejBetegnelseHierarkiListeHentI request
    );

    @WebResult(name = "USKoeretoejArtListeHent_O", targetNamespace = "http://skat.dk/dmr/2007/05/31/", partName = "Response")
    @WebMethod(action = "getUSKoeretoejArtListeHent")
    public USKoeretoejArtListeHentO getUSKoeretoejArtListeHent(
        @WebParam(partName = "Request", name = "USKoeretoejArtListeHent_I", targetNamespace = "http://skat.dk/dmr/2007/05/31/")
        USKoeretoejArtListeHentI request
    );

    @WebResult(name = "USNormTypeListeHent_O", targetNamespace = "http://skat.dk/dmr/2007/05/31/", partName = "Response")
    @WebMethod(action = "getUSNormTypeListeHent")
    public USNormTypeListeHentO getUSNormTypeListeHent(
        @WebParam(partName = "Request", name = "USNormTypeListeHent_I", targetNamespace = "http://skat.dk/dmr/2007/05/31/")
        USNormTypeListeHentI request
    );

    @WebResult(name = "USTilladelseTypeListeHent_O", targetNamespace = "http://skat.dk/dmr/2007/05/31/", partName = "Response")
    @WebMethod(action = "getUSTilladelseTypeListeHent")
    public USTilladelseTypeListeHentO getUSTilladelseTypeListeHent(
        @WebParam(partName = "Request", name = "USTilladelseTypeListeHent_I", targetNamespace = "http://skat.dk/dmr/2007/05/31/")
        USTilladelseTypeListeHentI request
    );

    @WebResult(name = "USSupplerendeKarrosseriTypeListeHent_O", targetNamespace = "http://skat.dk/dmr/2007/05/31/", partName = "Response")
    @WebMethod(action = "getUSSupplerendeKarrosseriTypeListeHent")
    public USSupplerendeKarrosseriTypeListeHentO getUSSupplerendeKarrosseriTypeListeHent(
        @WebParam(partName = "Request", name = "USSupplerendeKarrosseriTypeListeHent_I", targetNamespace = "http://skat.dk/dmr/2007/05/31/")
        USSupplerendeKarrosseriTypeListeHentI request
    );

    @WebResult(name = "USKoeretoejAnvendelseListeHent_O", targetNamespace = "http://skat.dk/dmr/2007/05/31/", partName = "Response")
    @WebMethod(action = "getUSKoeretoejAnvendelseListeHent")
    public USKoeretoejAnvendelseListeHentO getUSKoeretoejAnvendelseListeHent(
        @WebParam(partName = "Request", name = "USKoeretoejAnvendelseListeHent_I", targetNamespace = "http://skat.dk/dmr/2007/05/31/")
        USKoeretoejAnvendelseListeHentI request
    );

    @WebResult(name = "USKoeretoejTekniskDataHent_O", targetNamespace = "http://skat.dk/dmr/2007/05/31/", partName = "Response")
    @WebMethod(action = "getUSKoeretoejTekniskDataHent")
    public USKoeretoejTekniskDataHentO getUSKoeretoejTekniskDataHent(
        @WebParam(partName = "Request", name = "USKoeretoejTekniskDataHent_I", targetNamespace = "http://skat.dk/dmr/2007/05/31/")
        USKoeretoejTekniskDataHentI request
    );

    @WebResult(name = "USKoeretoejUdstyrTypeListeHent_O", targetNamespace = "http://skat.dk/dmr/2007/05/31/", partName = "Response")
    @WebMethod(action = "getUSKoeretoejUdstyrTypeListeHent")
    public USKoeretoejUdstyrTypeListeHentO getUSKoeretoejUdstyrTypeListeHent(
        @WebParam(partName = "Request", name = "USKoeretoejUdstyrTypeListeHent_I", targetNamespace = "http://skat.dk/dmr/2007/05/31/")
        USKoeretoejUdstyrTypeListeHentI request
    );

    @WebResult(name = "USKoeretoejBlokeringAarsagTypeListeHent_O", targetNamespace = "http://skat.dk/dmr/2007/05/31/", partName = "Response")
    @WebMethod(action = "getUSKoeretoejBlokeringAarsagTypeListeHent")
    public USKoeretoejBlokeringAarsagTypeListeHentO getUSKoeretoejBlokeringAarsagTypeListeHent(
        @WebParam(partName = "Request", name = "USKoeretoejBlokeringAarsagTypeListeHent_I", targetNamespace = "http://skat.dk/dmr/2007/05/31/")
        USKoeretoejBlokeringAarsagTypeListeHentI request
    );

    @WebResult(name = "USDrivkraftTypeListeHent_O", targetNamespace = "http://skat.dk/dmr/2007/05/31/", partName = "Response")
    @WebMethod(action = "getUSDrivkraftTypeListeHent")
    public USDrivkraftTypeListeHentO getUSDrivkraftTypeListeHent(
        @WebParam(partName = "Request", name = "USDrivkraftTypeListeHent_I", targetNamespace = "http://skat.dk/dmr/2007/05/31/")
        USDrivkraftTypeListeHentI request
    );

    @WebResult(name = "USDispensationTypeListeHent_O", targetNamespace = "http://skat.dk/dmr/2007/05/31/", partName = "Response")
    @WebMethod(action = "getUSDispensationTypeListeHent")
    public USDispensationTypeListeHentO getUSDispensationTypeListeHent(
        @WebParam(partName = "Request", name = "USDispensationTypeListeHent_I", targetNamespace = "http://skat.dk/dmr/2007/05/31/")
        USDispensationTypeListeHentI request
    );

    @WebResult(name = "USForsikringStatusAendringListeHent_O", targetNamespace = "http://skat.dk/dmr/2007/05/31/", partName = "Response")
    @WebMethod(action = "getUSForsikringStatusAendringListeHent")
    public USForsikringStatusAendringListeHentO getUSForsikringStatusAendringListeHent(
        @WebParam(partName = "Request", name = "USForsikringStatusAendringListeHent_I", targetNamespace = "http://skat.dk/dmr/2007/05/31/")
        USForsikringStatusAendringListeHentI request
    );

    @WebResult(name = "KompenserTransSvar", targetNamespace = "http://skat.dk/dmr/2007/05/31/", partName = "Response")
    @WebMethod(action = "getKompenserTrans")
    public KompenserTransSvarType getKompenserTrans(
        @WebParam(partName = "Request", name = "KompenserTrans", targetNamespace = "http://skat.dk/dmr/2007/05/31/")
        KompenserTransType request
    );

    @WebResult(name = "USForsikringSelskabListeHent_O", targetNamespace = "http://skat.dk/dmr/2007/05/31/", partName = "Response")
    @WebMethod(action = "getUSForsikringSelskabListeHent")
    public USForsikringSelskabListeHentO getUSForsikringSelskabListeHent(
        @WebParam(partName = "Request", name = "USForsikringSelskabListeHent_I", targetNamespace = "http://skat.dk/dmr/2007/05/31/")
        USForsikringSelskabListeHentI request
    );

    @WebResult(name = "USKoeretoejArtAnvendelseListeHent_O", targetNamespace = "http://skat.dk/dmr/2007/05/31/", partName = "Response")
    @WebMethod(action = "getUSKoeretoejArtAnvendelseListeHent")
    public USKoeretoejArtAnvendelseListeHentO getUSKoeretoejArtAnvendelseListeHent(
        @WebParam(partName = "Request", name = "USKoeretoejArtAnvendelseListeHent_I", targetNamespace = "http://skat.dk/dmr/2007/05/31/")
        USKoeretoejArtAnvendelseListeHentI request
    );

    @WebResult(name = "USFarveTypeListeHent_O", targetNamespace = "http://skat.dk/dmr/2007/05/31/", partName = "Response")
    @WebMethod(action = "getUSFarveTypeListeHent")
    public USFarveTypeListeHentO getUSFarveTypeListeHent(
        @WebParam(partName = "Request", name = "USFarveTypeListeHent_I", targetNamespace = "http://skat.dk/dmr/2007/05/31/")
        USFarveTypeListeHentI request
    );

    @WebResult(name = "USKarrosseriTypeListeHent_O", targetNamespace = "http://skat.dk/dmr/2007/05/31/", partName = "Response")
    @WebMethod(action = "getUSKarrosseriTypeListeHent")
    public USKarrosseriTypeListeHentO getUSKarrosseriTypeListeHent(
        @WebParam(partName = "Request", name = "USKarrosseriTypeListeHent_I", targetNamespace = "http://skat.dk/dmr/2007/05/31/")
        USKarrosseriTypeListeHentI request
    );
}
